apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: infrastore
  namespace: infrastore
spec:
  minAvailable: 1  
  selector:
    matchLabels:
      app: infrastore
  unhealthyPodEvictionPolicy: AlwaysAllow
