apiVersion: v1
kind: ResourceQuota
metadata:
  name: infrastore-quota
  namespace: infrastore
spec:
  hard:
    # CPU quotas
    requests.cpu: "5"      # Total requested CPU
    limits.cpu: "15"        # Total CPU limits
    
    # Memory quotas
    requests.memory: "5Gi"  # Total requested memory
    limits.memory: "15Gi"    # Total memory limits
    
    # Pod count
    pods: "15"              # Max pods in namespace
    
    # Storage
    persistentvolumeclaims: "5"  # Max PVCs
    requests.storage: "50Gi"    # Max storage
